#!/bin/bash

# Description: Run this script with sudo.

set -o errexit
set -o nounset
set -o pipefail

if [[ $EUID != 0 ]]; then
    echo "Error: Run this script with sudo." >&2
    exit 1
fi

apt-get clean --yes
