#!/bin/bash
# Mute audio by setting its volume zero

set -o errexit
set -o nounset
set -o pipefail

declare -r input="${1:?Usage: ${0##*/} SOURCE_PATH}"
declare -r output="${input%.*}-mute.${input#*.}"
declare -ar ffmpeg_global_options=(-loglevel error -y)
declare -ar ffmpeg_output_options=(-c:v copy -af volume=0)

ffmpeg "${ffmpeg_global_options[@]}" \
    -i "$input" \
    "${ffmpeg_output_options[@]}" "$output"
touch -r "$input" "$output"
