#!/bin/bash
# <https://deepgram.com/learn/ffmpeg-beginners>

declare -r input="${1:?Usage: ${0##*/} SOURCE_PATH}"
declare -r output="${input%.*}-reduce-noise.${input#*.}"
declare -ar ffmpeg_global_options=(-loglevel error -y)
declare -ar ffmpeg_output_options=(
    -c:v copy
    -af highpass=f=200,lowpass=f=3000)

ffmpeg "${ffmpeg_global_options[@]}" \
    -i "$input" \
    "${ffmpeg_output_options[@]}" "$output"
