#!/bin/bash
# backup-ssd: Back up important contents of my PC's SSD to an external HHD.
#
# Usage:
# sudo ./backup-ssd

set -o errexit
set -o nounset
set -o pipefail

if [ "$(whoami)" != "root" ] ; then
    echo "Run this script with sudo" >&2
    exit 1
fi

declare -r target_user="${SUDO_USER:-$USER}"
declare -r mount_dest_drive_letter="E"
declare -r mount_dest="/mnt/${mount_dest_drive_letter,,}"
declare -r dest="${mount_dest}/backup"

declare -r uid=$(id -u $target_user)
declare -r gid=$(id -g $target_user)

mkdir -p "${mount_dest}"
chown -R ${uid}:${gid} "${mount_dest}"
chmod -R 777 "${mount_dest}"
mount -t drvfs "${mount_dest_drive_letter^^}:" "${mount_dest}" -o metadata,uid=${uid},gid=${gid}

declare -r src="/mnt/c/Users/${target_user}"
declare -ar backup_dirs=(
    "${src}/AppData/Roaming/GIMP/3.0"
    "${src}/AppData/Roaming/inkscape"
    "${src}/AppData/Roaming/LibreOffice/4/user"
    "${src}/devel"
    "${src}/Documents"
    "${src}/Music"
    "${src}/Pictures"
    "${src}/Videos")

declare -r rsync_options="-azvh"  # -n
rsync ${rsync_options} --exclude={dotfiles/,tmp/} "${backup_dirs[@]}" "${dest}"

umount "${mount_dest}"
