#!/bin/bash
# backup-ssd: Back up important contents of my PC's SSD to an external HHD.
#
# Usage:
# sudo ./backp-ssd

if [ "$(whoami)" != "root" ] ; then
    echo "Run this script with sudo" >&2
    exit 1
fi

declare -r target_user="${SUDO_USER}"  # "${SUDO_USER:-$USER}"
declare -r rsync_options="-azvh"  # -n
declare -r mount_dest="/mnt/d"

declare -r src="/mnt/c/Users/${target_user}"
declare -r dest="${mount_dest}/Users/${target_user}"

mkdir -p "${mount_dest}"
mount -t drvfs D: "${mount_dest}"

rsync ${rsync_options} --exclude={dotfiles/,tmp/} \
    "${src}/devel" \
    "${src}/Documents" \
    "${src}/Music" \
    "${src}/Pictures" \
    "${src}/Videos" \
    "${dest}"

#rsync -azvh -n /mnt/c/Users/work/AppData/Roaming ${dest}/AppData
