#!/bin/bash

# fzf-docker-images: List docker images in an fzf interface.
#
# Examples:
#  fzf-docker-images | xargs docker image push
#  fzf-docker-images --filter="image_name" | xargs docker rmi

docker images --format "{{.Repository}} {{.Tag}} {{.ID}}" "$@" |
  column -t |
  fzf -m --accept-nth=3 \
    --border --border-label="docker images" --border-label-pos=4 \
    --header-border horizontal \
    --info=inline-right \
    --reverse
