#!/bin/bash
# fzf-color: CLI color-picker powered by fzf.

# Resources:
# - <https://man.archlinux.org/man/fzf.1.en>
# - <https://stackoverflow.com/questions/74589665/how-to-print-rgb-colour-to-the-terminal>
# - <https://askubuntu.com/questions/558280/changing-colour-of-text-and-background-of-terminal>
# - <https://developer.mozilla.org/en-US/docs/Web/CSS/color_value>

set -o errexit
set -o nounset
set -o pipefail

script_dir="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
declare -r script_dir

# aliceblue #f0f8ff
# antiquewhite #faebd7
# aqua #00ffff
# aquamarine #7fffd4
# ...
declare -r color_table_source="$script_dir/colors.txt"

declare -r preview='echo TODO: fancy preview of {2}'

# shellcheck disable=SC2016
declare -r open_color_hex='
color_code={2}
code_without_hash_sign=${color_code#\#}
xdg-open https://www.color-hex.com/color/${code_without_hash_sign}
'

awk '{
    name = $1
    color_code = $2
    r = strtonum("0x" substr(color_code, 2, 2))
    g = strtonum("0x" substr(color_code, 4, 2))
    b = strtonum("0x" substr(color_code, 6, 2))
    printf "\033[48;2;%d;%d;%dm \033[0m %s %s\n", r, g, b, name, color_code
}
' "$color_table_source" | column -t -s ' ' | \
    fzf --ansi \
        --accept-nth=1,2 \
        --bind='enter:become:echo {1} {2}' \
        --bind="ctrl-o:execute-silent:$open_color_hex" \
        --bind 'alt-r:toggle-raw' \
        --border --border-label=" CSS named colors " --border-label-pos=4 \
        --header="Ctrl+O: Open www.Color-Hex.com" --header-border horizontal \
        --info=inline-right \
        --layout=reverse \
        --preview="$preview" \
        --preview-window=right:50%:nowrap \
