#!/bin/bash

# gh-star: Star a repository for the authenticated user.
# <https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28>
#
# Example:
# $ gh-star showa-yojyo/dqbook

if [[ $# -lt 1 ]] ; then
    echo Usage: ${0##*/} ACCOUNT/REPO >&2
    exit 2
fi

declare -r target="$1"

gh api --method PUT \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /user/starred/${target}
