#!/bin/bash

# ms-settings: A simple launcher of Windows Settings App.

set -o errexit
set -o nounset
set -o pipefail

declare -r script_dir=$(realpath $(dirname "${BASH_SOURCE[0]}"))
declare -r settings_table_source="$script_dir/ms-settings.txt"

fzf --height=40% \
    --border --border-label "Windows Settings" --border-label-pos=3 \
    --color hl:underline,hl+:underline \
    --no-hscroll \
    --layout=reverse \
    --bind 'enter:become(wslview ms-settings:{})' < "$settings_table_source"
