#!/bin/bash

echo '
about
activation
appsfeatures
appsforwebsites
assignedaccess
autoplay
backup
batterysaver
bluetooth
camera
clipboard
colors
connecteddevices
crossdevice
dateandtime
defaultapps
delivery-optimization
developers
deviceencryption
devices-touchpad
display
easeofaccess-audio
easeofaccess-closedcaptioning
easeofaccess-colorfilter
easeofaccess-cursor
easeofaccess-display
easeofaccess-hearingaids
easeofaccess-highcontrast
easeofaccess-keyboard
easeofaccess-magnifier
easeofaccess-mouse
easeofaccess-mousepointer
easeofaccess-narrator
easeofaccess-speechrecognition
easeofaccess-visualeffects
emailandaccounts
energyrecommendations
findmydevice
gaming-gamebar
gaming-gamedvr
gaming-gamemode
keyboard
lockscreen
maps
mobile-devices
mousetouchpad
multitasking
network-advancedsettings
network-airplanemode
network-dialup
network-ethernet
network-mobilehotspot
network-proxy
network-status
network-vpn
network-wifi
notifications
optionalfeatures
otherusers
personalization
personalization-background
personalization-start
personalization-start-places
printers
privacy
privacy-accountinfo
privacy-appdiagnostics
privacy-broadfilesystemaccess
privacy-calendar
privacy-callhistory
privacy-contacts
privacy-customdevices
privacy-documents
privacy-downloadsfolder
privacy-email
privacy-feedback
privacy-general
privacy-location
privacy-messaging
privacy-microphone
privacy-musiclibrary
privacy-notifications
privacy-phonecalls
privacy-pictures
privacy-radios
privacy-speech
privacy-speechtyping
privacy-tasks
privacy-videos
privacy-voiceactivation
privacy-webcam
project
quiethours
recovery
remotedesktop
search
signinoptions
sound
speech
startupapps
storagepolicies
storagesense
taskbar
themes
troubleshoot
usb
videoplayback
windowsdefender
windowsinsider
windowsupdate
windowsupdate-history
windowsupdate-optionalupdates
workplace
yourinfo
' | fzf --bind 'enter:become(wslview ms-settings:{})'
