#!/bin/bash

# Example: mydump /path/to/DQ3.smc 0x030900 0x09 0x34

declare -r rom="$1"
declare -r offset="$2"
declare -r len="$3"
declare -r num="$4"

hd -v -s $offset -n $(($len * $num)) -e "$(($len))/1 \"%02X\" \"\n\"" "$rom"
