#!/bin/bash

# pdf-optimize: compress a PDF file

# Reference:
# * Reduce PDF File Size in Linux
#   <https://www.digitalocean.com/community/tutorials/reduce-pdf-file-size-in-linux>

declare -r input="${1:?Usage: ${0##*/} INPUT_PDF_PATH}"
declare -r workpath="$(mktemp XXXXXXXX.pdf)"
declare -r gs_options="-sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dBATCH"

gs $gs_options -sOutputFile="$workpath" "$input"
chmod =rw "$workpath"
touch -r "$input" "$workpath"
mv -f "$workpath" "$input"
