#!/usr/bin/env python

"""
Make landscape images portrait by using PIL (asyncio version)
"""

from __future__ import annotations
import asyncio
import logging
import pathlib
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

import click
from PIL import Image


__version__ = "1.4"
logger = logging.getLogger(__name__)


async def rotate_image(filename: pathlib.Path) -> None:
    """Consumer coroutine"""

    logger.info(f"Working on {filename}")
    try:
        image = Image.open(filename)
        if image.width <= image.height:
            # already portrait
            logger.info(f"Skip {filename}")
            return
        image_new = image.rotate(-90, expand=True)
        logger.info(f"Saving {filename}")
        image_new.save(filename)
    except Exception as e:
        # PIL.UnidentifiedImageError: The image cannot be opened and identified.
        # ValueError: The output format could not be determined from the file name.
        # OSError: The file may have been created, and may contain partial data.
        logger.warning(f"Warning: {e}")


async def amain(filename: Sequence[pathlib.Path], num_consumers: int) -> None:
    """
    Asynchronous main coroutine.

    :param filename: Iterable of image filenames
    :param num_consumers: Number of consumers
    """

    async with asyncio.TaskGroup() as tg:
        semaphore = asyncio.Semaphore(num_consumers)
        for img in filename:
            async with semaphore:
                tg.create_task(rotate_image(img))
        logger.info("All task requests sent")
    logger.info("All work completed")


@click.command()
@click.argument(
    "filename",
    nargs=-1,
    type=click.Path(
        exists=True,
        path_type=pathlib.Path,
    ),
)
@click.help_option(
    help="display this message and exit",
)
@click.version_option(
    __version__,
    help="output version information and exit",
)
@click.option(
    "-v",
    "--verbose",
    is_flag=True,
    default=False,
    help="output a diagnostic for every file processed",
)
@click.option(
    "-n",
    "--num-consumers",
    type=int,
    default=3,
    help="the number of consumers",
)
def main(
    filename: Sequence[pathlib.Path],
    num_consumers: int,
    verbose: bool,
) -> None:
    """Make landscape images portrait."""

    logger.addHandler(logging.StreamHandler(sys.stderr))
    if verbose:
        logger.setLevel(logging.DEBUG)
    asyncio.run(amain(filename, num_consumers))


if __name__ == "__main__":
    main()
