#!/usr/bin/env python

"""
Make landscape images portrait by using PIL (asyncio version)
"""

from __future__ import annotations
import asyncio
import pathlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

import click
from PIL import Image


__version__ = "1.1"


async def generate_images(
    queue: asyncio.Queue,
    filename: Iterable[pathlib.Path],
) -> None:
    """Producer coroutine"""

    for f in filename:
        await queue.put(f)

    click.echo("All task requests sent")


async def rotate_image(queue: asyncio.Queue) -> None:
    """Consumer coroutine"""

    while True:
        filename: str = await queue.get()
        click.echo(f"Working on {filename}")
        try:
            image = Image.open(filename)
            if image.width <= image.height:
                # already portrait
                click.echo(f"Skip {filename}")
                continue

            image_new = image.rotate(-90, expand=True)
            click.echo(f"Saving {filename}")
            image_new.save(filename)
        finally:
            queue.task_done()


async def terminate_consumers(consumers: Iterable[asyncio.Task]) -> None:
    """Clean up consumers"""

    for consumer in consumers:
        consumer.cancel()

    await asyncio.gather(*consumers, return_exceptions=True)


async def amain(filename: Sequence[pathlib.Path]) -> None:
    # Producer/consumer pattern
    queue: asyncio.Queue = asyncio.Queue()

    # turn on the rotate_image thread
    consumers = [asyncio.create_task(rotate_image(queue)) for _ in range(3)]
    await generate_images(queue, filename)

    # block until all tasks are done
    await queue.join()
    click.echo("All work completed")

    await terminate_consumers(consumers)


@click.command()
@click.argument(
    "filename",
    nargs=-1,
    type=click.Path(
        exists=True,
        path_type=pathlib.Path,
    ),
)
@click.help_option(
    help="display this message and exit",
)
@click.version_option(
    __version__,
    help="output version information and exit",
)
def main(filename: Sequence[pathlib.Path]) -> None:
    """Make landscape images portrait."""

    asyncio.run(amain(filename))


if __name__ == "__main__":
    main()
