#!/bin/bash

# See <https://tldp.org/LDP/abs/html/sample-bashrc.html>

set -o errexit
set -o nounset
set -o pipefail

declare -r script=${0##*/}

[[ $# -ne 2 ]] && echo "$script: specify two paths" >&2 && exit 2
[[ ! -e $1 ]] && echo "$script: $1 does not exist" >&2 && exit 2
[[ ! -e $2 ]] && echo "$script: $2 does not exist" >&2 && exit 2

declare -r tmpfile=tmp.$$
mv "$1" $tmpfile
mv "$2" "$1"
mv $tmpfile "$2"
