#!/bin/bash

# Drop first seconds from a video

declare -r input="${1:?Usage: ${0##*/} INPUT_VIDEO_PATH SECONDS}"
declare -r seconds="${2:-1}"
declare -r output="${input%.*}-drop-first.${input##*.}"

declare -r ffmpeg_global_options="-loglevel error -y"
declare -r ffmpeg_input_options="-ss $seconds"
declare -r ffmpeg_output_options="-c copy"

ffmpeg $ffmpeg_global_options $ffmpeg_input_options -i \
  "$input" $ffmpeg_output_options "$output"

touch -r "$input" "$output"
