#!/bin/bash
# Speed up a video with audio.
#
# Referenece: Is it possible to speed up video with audio using ffmpeg, without
# changing audio pitch? <https://superuser.com/questions/1324525/>

declare -r input="${1:?Usage: ${0##*/} INPUT_VIDEO_PATH SPEED_FACTOR}"
declare -r speed="${2:-1}"
declare -r output="${input%.*}-${speed}x-speed.${input#*.}"

declare -ar ffmpeg_global_options=(-loglevel error -y)
declare -ar ffmpeg_input_options=()
declare -ar ffmpeg_output_options=(
  -vf "setpts=(PTS-STARTPTS)/${speed}"
  -af "atempo=${speed}")

ffmpeg "${ffmpeg_global_options[@]}" \
  "${ffmpeg_input_options[@]}" -i "$input" \
  "${ffmpeg_output_options[@]}" "$output"
touch -r "$input" "$output"
