#!/bin/bash

# Drop first seconds from a video

set -o errexit
set -o nounset
set -o pipefail

declare -r input="${1:?Usage: ${0##*/} SOURCE SECONDS}"
declare -r seconds="${2:-1}"
declare -r output="${input%.*}-drop-first.${input##*.}"

declare -ar ffmpeg_global_options=(-loglevel error -y)
declare -ar ffmpeg_input_options=(-ss $seconds)
declare -ar ffmpeg_output_options=(-c copy)

ffmpeg "${ffmpeg_global_options[@]}" \
  "${ffmpeg_input_options[@]}" -i "$input" \
  "${ffmpeg_output_options[@]}" "$output"
touch -r "$input" "$output"
