#!/bin/bash

# wsl-drop-cache: WIP

grep -q 'swap=0' /mnt/c/Users/$USER/.wslconfig
sudo sync; echo 3 | sudo tee /proc/sys/vm/drop_caches
if [ $? -ne 0 ] ; then
    sudo swapoff -a
    sudo swapon -a
fi
