#!/bin/bash

# wsl-drop-cache: try to reclaim more memory.
# Usage:
# sudo ./wsl-drop-cache

set -o errexit
set -o nounset
set -o pipefail

if [ "$(whoami)" != "root" ] ; then
    echo "Run this script with sudo" >&2
    exit 1
fi

# Flush writes and drop file system caches.
sync
echo 3 | tee /proc/sys/vm/drop_caches

# Disable all swaps from /proc/swaps.
swapoff -a

# Enable all swaps from /etc/fstab.
swapon -a
